name: Laravel CI process

on:
  push:
    branches: [main]
#KORACI
jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

    #DODAVANJE PHP-A
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, dom, fileinfo, sqlite3, pdo_sqlite
          coverage: none

    #DODAVANJE COMPOSERA I LARAVELA
      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

    #DODAVANJE npm paketa

      - name: Install NPM dependencies
        run: npm install

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

    #DODAVANJE build-a za produkciju
      - name: Build Vite assets
        run: npm run build

    #PROVJERA LARAVEL VERZIJE
      - name: Verify Laravel application
        run: php artisan --version

    #CISCENJE LARAVEL CACHE-A
      # - name: Clear Laravel Cache
      #   run: php artisan optimize:clear

    #POPIS RUTA
      - name: Popis ruta
        run: php artisan route:list